global using AutoFixture;
global using AutoFixture.AutoNSubstitute;
global using AutoFixture.NUnit3;
global using Endava.TechCourse.BankApp.Tests.Common;
global using EntityFrameworkCore.AutoFixture.Core;
global using EntityFrameworkCore.AutoFixture.Sqlite;
global using FluentAssertions;
global using FluentAssertions.Execution;
global using NUnit.Framework;